---
    name: Deploy Lambda Function
    
    on:
      push:
        branches:
          - main
    
    jobs:
      deploy:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v2
    
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.10'
    
          - name: Install AWS CLI
            run: pip install awscli
    
          - name: Zip Lambda Function Code
            run: |
              cd createExpense
              zip -r ../lambda_function.zip .
    
          - name: Deploy to AWS Lambda
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: eu-west-1
            run: |
              aws configure set region $AWS_REGION
              aws lambda update-function-code \
                --function-name addExpense \
                --zip-file fileb://lambda_function.zip
    
